### ISSUE TITLE
Assertion `t >= 0 && t < n_classes` failed    RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by pustar** [milesial/Pytorch-UNet#258]
when I have 3 classes, the net pred maximum label =  tensor(3.0743, device='cuda:0', grad_fn=<MaxBackward1>)

RuntimeError: CUDA error: device-side assert triggered

/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [725,0,0] Assertion `t >= 0 && t < n_classes` failed

**Comment by milesial** [comment]
what do you mean by 'maximum label' ? If you have 3 classes you should change n_classes to 3 (or 4 if you include background).

**Comment by milesial** [comment]
Closing, as this issue is now outdated after the recent code refactor.

**Comment by ljmkgbkq** [comment]
I met the same problem. I solved this problem by adding one to args "classes".

**Comment by algwang** [comment]
> 我遇到了同样的问题。我通过在 args “classes” 中添加一个来解决这个问题。

Could you explain how it is done?
