### ISSUE TITLE
How to resolve "RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`"?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [milesial/Pytorch-UNet#298]
Hi,
    I have trained your code successfully by using "python train.py --amp" and the prediction is also normal. However, when I use my own dataset and make sure it is loaded properly in utils/data_loading.py, the following error has been encountered:
![700](https://user-images.githubusercontent.com/72843232/134800925-68749b99-d232-4dfa-b80e-2dbd4d02f807.png)
![701](https://user-images.githubusercontent.com/72843232/134800932-e908d645-73c3-4c3d-8947-10b13ce0b2f4.png)

    Moreover, the batch size is "1", n_channels is "3" and n_classes is "4".
![703](https://user-images.githubusercontent.com/72843232/134800996-33fd7e93-7001-41f5-8641-74dc818c0042.png)

    So, could you pls help to give me some suggestions on how to resolve the "CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`"? Many Thanks!

**Comment by k1l1an** [comment]
One possible reason is that you're running out of GPU memory. Doublecheck with "watch -n1 nvidia-smi" in separate terminal. If so your only option is decreasing the image resolution, as your batch size is already 1.

**Comment by busrakb** [comment]
![Capture](https://user-images.githubusercontent.com/25199144/142882432-3fb9252f-9d48-40c8-81d0-3b7af39048ce.PNG)
Hi ,
i got same error. How i will solve problem. Can you help me, please?

**Comment by TankredO** [comment]
I encountered the same problem and could solve it by setting the correct number of classes in `train.py` (`net = UNet(n_channels=3, n_classes=1, bilinear=True)`).

**Comment by sisyphos-1000** [comment]
Have you tried without the amp flag? From my experience, automatic mixed precision can cause problems depending on the device.

**Comment by TankredO** [comment]
I had the same issue with a custom dataset. The problem was that my binary masks were in the wrong format, i.e, each pixel was either 0 or 255 instead of 0 or 1.

**Comment by milesial** [comment]
Duplicate of https://github.com/milesial/Pytorch-UNet/issues/372
