### ISSUE TITLE
How to solve "RuntimeError: CUDA error: device-side assert triggered"

### ISSUE THREAD

**Issue by littlestar-xxy** [milesial/Pytorch-UNet#324]
I have tried the code with carvana dataset and it worked successfully, then I tried my own dataset but failed with above problem. could anyone helps me fix it? Appreciate your help!

**Comment by littlestar-xxy** [comment]
with output.log describes as:

INFO: Starting training:
        Epochs:          5
        Batch size:      4
        Learning rate:   1e-05
        Training size:   1108
        Validation size: 123
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: True
Epoch 1/5:   0%|                                                                                                                                                                  | 0/1108 [00:04<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    train_net(net=net,
  File "train.py", line 96, in train_net
    F.one_hot(true_masks, net.n_classes).permute(0, 3, 1, 2).float(),
RuntimeError: CUDA error: device-side assert triggered

**Comment by littlestar-xxy** [comment]
I think there exists something wrong with the function 'preprocess' in class BasicDataset  in data_loading.py. I change 'if not is_mask:' into 'if is_mask:' due to the error information in terminal. After I make my binary mask, the pixel is 0 or 255, but it should be 0 or 1 when it was sent to torch.nn.functional.onehot to match my 2 classes classification.

**Comment by qslia** [comment]
I have meeting this issue right now, and I solved it by turning custom_mask.jpg to custom_mask.gif. Because jpg file has channels (height, weight, channel), and gif file only has dimension without depth (height, weight)

**Comment by andanders** [comment]
Hi @littlestar-xxy, I ran into the same problem. My .gif mask has tensor values 0, 255. Did you change your script?
My gif is 8 bit, single layer (according to GIMP any way).

**Comment by littlestar-xxy** [comment]
I'm sorry that I don't remember it clearly, it has been a long time since I
debugged the code.  I only have some impression on changing my mask from
0-255 to 0-1 (different classes with different values between 0-1)

andanders ***@***.***> 于2022年7月12日周二 03:25写道：

**Comment by tharindu326** [comment]
> if is_mas

My ground truth have 0 or 255 values for my background and class. It seems like in `def preprocess(pil_img, scale, is_mask)` you need to make mask pixels either 0 or 1. So I  modified the function as follow and it started to working fine. 



     def preprocess(pil_img, scale, is_mask):
        w, h = pil_img.size
        newW, newH = int(scale * w), int(scale * h)
        assert newW > 0 and newH > 0, 'Scale is too small, resized images would have no pixel'
        pil_img = pil_img.resize((newW, newH), resample=Image.NEAREST if is_mask else Image.BICUBIC)
        img_ndarray = np.asarray(pil_img)

        if not is_mask:
            if img_ndarray.ndim == 2:
                img_ndarray = img_ndarray[np.newaxis, ...]
            else:
                img_ndarray = img_ndarray.transpose((2, 0, 1))

            img_ndarray = img_ndarray / 255
        else:
            img_ndarray = img_ndarray / 255     ### this line was added 

        return img_ndarray
