### ISSUE TITLE
RuntimeError: cuda runtime error

### ISSUE THREAD

**Issue by tengerye** [milesial/Pytorch-UNet#8]
My OS is Ubuntu 16.04.4 LTS, and Cuda is V7.5.17. My Pytorch is 0.4.

My script to run is:
`predict.py --cpu -i ~/Desktop/download.jpg -o output.jpg`

But I encounter the following error:
```
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=51 error=30 : unknown error
Traceback (most recent call last):
  File "/projects/segmentation/Pytorch-UNet/predict.py", line 88, in <module>
    net.load_state_dict(torch.load(args.model))
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
RuntimeError: cuda runtime error (30) : unknown error at torch/csrc/cuda/Module.cpp:51
```

**Comment by tengerye** [comment]
After rebooting my desktop, my error message altered to:

```
THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=51 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "gprojects/segmentation/Pytorch-UNet/predict.py", line 88, in <module>
    net.load_state_dict(torch.load(args.model))
  File "ganaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "ganaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "ganaconda3/lib/python3.6/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "ganaconda3/lib/python3.6/site-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "ganaconda3/lib/python3.6/site-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "ganaconda3/lib/python3.6/site-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "ganaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:51
```

**Comment by tengerye** [comment]
I have CUDA but I don't have nvidia GPU, I have only Intel GPU. I don't know if it causes this problem.

**Comment by milesial** [comment]
CUDA only works with NVIDIA graphics cards, you can try predicting with the cpu only !

**Comment by tengerye** [comment]
Thank you for your kind reply. I did try to predict with the CPU only, but still get error as above. I also tried to re-install pytorch with CPU only. But still get error:
```
Traceback (most recent call last):
  File "/projects/segmentation/Pytorch-UNet/predict.py", line 88, in <module>
    net.load_state_dict(torch.load(args.model))
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 437, in persistent_load
    data_type(size), location)
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 88, in default_restore_location
    result = fn(storage, location)
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 70, in _cuda_deserialize
    return obj.cuda(device)
  File "/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 68, in _cuda
    with torch.cuda.device(device):
  File "/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 225, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'
```

**Comment by tengerye** [comment]
Problem solved by changing the loading to:
`net.load_state_dict(torch.load(args.model, map_location='cpu'))`
